# Generated by Django 5.1.7 on 2025-03-23 23:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[[0, 0]], size=None),
        ),
    ]
