# Generated by Django 5.1.7 on 2025-03-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0002_alter_user_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sprite',
            field=models.IntegerField(default=1),
        ),
    ]
