# Generated by Django 5.1.7 on 2025-03-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0003_user_sprite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='catchingExp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='catchingSkill',
            field=models.IntegerField(default=0),
        ),
    ]
