# Generated by Django 5.1.7 on 2025-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0004_user_catchingexp_user_catchingskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posDirection',
            field=models.CharField(default='up', max_length=10),
        ),
    ]
