# Generated by Django 5.1.7 on 2025-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0005_alter_user_posdirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posMap',
            field=models.CharField(default='map', max_length=50),
        ),
    ]
