# Generated by Django 5.1.7 on 2025-03-24 20:45

import django.contrib.postgres.fields
import testsocket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0006_alter_user_posmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=testsocket.models.get_default_inventory, size=None),
        ),
    ]
