# Generated by Django 5.1.7 on 2025-03-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0007_alter_user_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentSlot',
            field=models.IntegerField(default=0),
        ),
    ]
