# Generated by Django 5.1.7 on 2025-03-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0008_user_currentslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentSlot',
            field=models.CharField(default='weaponSlot', max_length=10),
        ),
    ]
