# Generated by Django 5.1.7 on 2025-03-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsocket', '0009_alter_user_currentslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='armorSlot',
            new_name='armor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hoeSlot',
            new_name='hoe',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pickSlot',
            new_name='pickaxe',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='shovelSlot',
            new_name='shovel',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='weaponSlot',
            new_name='weapon',
        ),
    ]
